# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QSize(1280, 720))
        MainWindow.setMaximumSize(QSize(1280, 720))
        MainWindow.setBaseSize(QSize(1280, 720))
        self.actionFrom_this_pc = QAction(MainWindow)
        self.actionFrom_this_pc.setObjectName(u"actionFrom_this_pc")
        self.actionJk_I_ran_out_of_time = QAction(MainWindow)
        self.actionJk_I_ran_out_of_time.setObjectName(u"actionJk_I_ran_out_of_time")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.xRotSlider = QSlider(self.centralwidget)
        self.xRotSlider.setObjectName(u"xRotSlider")
        self.xRotSlider.setGeometry(QRect(280, 610, 981, 21))
        self.xRotSlider.setOrientation(Qt.Horizontal)
        self.yRotSlider = QSlider(self.centralwidget)
        self.yRotSlider.setObjectName(u"yRotSlider")
        self.yRotSlider.setGeometry(QRect(280, 630, 981, 21))
        self.yRotSlider.setOrientation(Qt.Horizontal)
        self.zRotSlider = QSlider(self.centralwidget)
        self.zRotSlider.setObjectName(u"zRotSlider")
        self.zRotSlider.setGeometry(QRect(280, 650, 981, 21))
        self.zRotSlider.setMaximum(99)
        self.zRotSlider.setOrientation(Qt.Horizontal)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(180, 610, 91, 20))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(180, 630, 91, 20))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(180, 650, 91, 20))
        self.toggleAnimationPushButton = QPushButton(self.centralwidget)
        self.toggleAnimationPushButton.setObjectName(u"toggleAnimationPushButton")
        self.toggleAnimationPushButton.setGeometry(QRect(30, 630, 121, 21))
        self.redSlider = QSlider(self.centralwidget)
        self.redSlider.setObjectName(u"redSlider")
        self.redSlider.setGeometry(QRect(10, 150, 160, 16))
        self.redSlider.setMinimum(0)
        self.redSlider.setMaximum(255)
        self.redSlider.setOrientation(Qt.Horizontal)
        self.blueSlider = QSlider(self.centralwidget)
        self.blueSlider.setObjectName(u"blueSlider")
        self.blueSlider.setGeometry(QRect(10, 230, 160, 16))
        self.blueSlider.setMinimum(0)
        self.blueSlider.setMaximum(255)
        self.blueSlider.setOrientation(Qt.Horizontal)
        self.greenSlider = QSlider(self.centralwidget)
        self.greenSlider.setObjectName(u"greenSlider")
        self.greenSlider.setGeometry(QRect(10, 190, 160, 16))
        self.greenSlider.setMinimum(0)
        self.greenSlider.setMaximum(255)
        self.greenSlider.setOrientation(Qt.Horizontal)
        self.alphaSlider = QSlider(self.centralwidget)
        self.alphaSlider.setObjectName(u"alphaSlider")
        self.alphaSlider.setGeometry(QRect(10, 270, 160, 16))
        self.alphaSlider.setMinimum(0)
        self.alphaSlider.setMaximum(255)
        self.alphaSlider.setOrientation(Qt.Horizontal)
        self.redSliderLabel = QLabel(self.centralwidget)
        self.redSliderLabel.setObjectName(u"redSliderLabel")
        self.redSliderLabel.setGeometry(QRect(10, 130, 81, 16))
        self.redSliderLabel.setStyleSheet(u"color: red")
        self.alphaSliderLabel = QLabel(self.centralwidget)
        self.alphaSliderLabel.setObjectName(u"alphaSliderLabel")
        self.alphaSliderLabel.setGeometry(QRect(10, 250, 111, 16))
        self.greenSliderLabel = QLabel(self.centralwidget)
        self.greenSliderLabel.setObjectName(u"greenSliderLabel")
        self.greenSliderLabel.setGeometry(QRect(10, 170, 81, 16))
        self.greenSliderLabel.setStyleSheet(u"color: green")
        self.blueSliderLabel = QLabel(self.centralwidget)
        self.blueSliderLabel.setObjectName(u"blueSliderLabel")
        self.blueSliderLabel.setGeometry(QRect(10, 210, 81, 16))
        self.blueSliderLabel.setStyleSheet(u"color: blue")
        self.shapeComboBox = QComboBox(self.centralwidget)
        self.shapeComboBox.addItem("")
        self.shapeComboBox.addItem("")
        self.shapeComboBox.addItem("")
        self.shapeComboBox.addItem("")
        self.shapeComboBox.setObjectName(u"shapeComboBox")
        self.shapeComboBox.setGeometry(QRect(10, 60, 151, 22))
        self.shapeComboBoxLabel = QLabel(self.centralwidget)
        self.shapeComboBoxLabel.setObjectName(u"shapeComboBoxLabel")
        self.shapeComboBoxLabel.setGeometry(QRect(10, 30, 151, 21))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.shapeComboBoxLabel.setFont(font)
        self.surfaceSlidersLabel = QLabel(self.centralwidget)
        self.surfaceSlidersLabel.setObjectName(u"surfaceSlidersLabel")
        self.surfaceSlidersLabel.setGeometry(QRect(10, 100, 151, 21))
        self.surfaceSlidersLabel.setFont(font)
        self.greenEdgeSliderLabel = QLabel(self.centralwidget)
        self.greenEdgeSliderLabel.setObjectName(u"greenEdgeSliderLabel")
        self.greenEdgeSliderLabel.setGeometry(QRect(10, 370, 81, 16))
        self.greenEdgeSliderLabel.setStyleSheet(u"color: green")
        self.greenEdgeSlider = QSlider(self.centralwidget)
        self.greenEdgeSlider.setObjectName(u"greenEdgeSlider")
        self.greenEdgeSlider.setGeometry(QRect(10, 390, 160, 16))
        self.greenEdgeSlider.setMinimum(0)
        self.greenEdgeSlider.setMaximum(255)
        self.greenEdgeSlider.setOrientation(Qt.Horizontal)
        self.blueEdgeSliderLabel = QLabel(self.centralwidget)
        self.blueEdgeSliderLabel.setObjectName(u"blueEdgeSliderLabel")
        self.blueEdgeSliderLabel.setGeometry(QRect(10, 410, 81, 16))
        self.blueEdgeSliderLabel.setStyleSheet(u"color: blue")
        self.redEdgeSliderLabel = QLabel(self.centralwidget)
        self.redEdgeSliderLabel.setObjectName(u"redEdgeSliderLabel")
        self.redEdgeSliderLabel.setGeometry(QRect(10, 330, 81, 16))
        self.redEdgeSliderLabel.setStyleSheet(u"color: red")
        self.edgeSlidersLabel = QLabel(self.centralwidget)
        self.edgeSlidersLabel.setObjectName(u"edgeSlidersLabel")
        self.edgeSlidersLabel.setGeometry(QRect(10, 300, 151, 21))
        self.edgeSlidersLabel.setFont(font)
        self.blueEdgeSlider = QSlider(self.centralwidget)
        self.blueEdgeSlider.setObjectName(u"blueEdgeSlider")
        self.blueEdgeSlider.setGeometry(QRect(10, 430, 160, 16))
        self.blueEdgeSlider.setMinimum(0)
        self.blueEdgeSlider.setMaximum(255)
        self.blueEdgeSlider.setOrientation(Qt.Horizontal)
        self.alphaEdgeSlider = QSlider(self.centralwidget)
        self.alphaEdgeSlider.setObjectName(u"alphaEdgeSlider")
        self.alphaEdgeSlider.setGeometry(QRect(10, 470, 160, 16))
        self.alphaEdgeSlider.setMinimum(0)
        self.alphaEdgeSlider.setMaximum(255)
        self.alphaEdgeSlider.setOrientation(Qt.Horizontal)
        self.alphaEdgeSliderLabel = QLabel(self.centralwidget)
        self.alphaEdgeSliderLabel.setObjectName(u"alphaEdgeSliderLabel")
        self.alphaEdgeSliderLabel.setGeometry(QRect(10, 450, 111, 16))
        self.redEdgeSlider = QSlider(self.centralwidget)
        self.redEdgeSlider.setObjectName(u"redEdgeSlider")
        self.redEdgeSlider.setGeometry(QRect(10, 350, 160, 16))
        self.redEdgeSlider.setMinimum(0)
        self.redEdgeSlider.setMaximum(255)
        self.redEdgeSlider.setOrientation(Qt.Horizontal)
        self.extrasLabel = QLabel(self.centralwidget)
        self.extrasLabel.setObjectName(u"extrasLabel")
        self.extrasLabel.setGeometry(QRect(10, 500, 181, 21))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setItalic(False)
        font1.setWeight(75)
        self.extrasLabel.setFont(font1)
        self.extrasLabel.setStyleSheet(u"color: red")
        self.rainbowModeRadioButton = QRadioButton(self.centralwidget)
        self.rainbowModeRadioButton.setObjectName(u"rainbowModeRadioButton")
        self.rainbowModeRadioButton.setGeometry(QRect(10, 530, 101, 19))
        self.rainbowModeSpeedSlider = QSlider(self.centralwidget)
        self.rainbowModeSpeedSlider.setObjectName(u"rainbowModeSpeedSlider")
        self.rainbowModeSpeedSlider.setGeometry(QRect(10, 580, 160, 16))
        self.rainbowModeSpeedSlider.setMinimum(1)
        self.rainbowModeSpeedSlider.setMaximum(50)
        self.rainbowModeSpeedSlider.setOrientation(Qt.Horizontal)
        self.rainbowModeSpeedSliderLabel = QLabel(self.centralwidget)
        self.rainbowModeSpeedSliderLabel.setObjectName(u"rainbowModeSpeedSliderLabel")
        self.rainbowModeSpeedSliderLabel.setGeometry(QRect(10, 560, 111, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1280, 20))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionJk_I_ran_out_of_time)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionFrom_this_pc.setText(QCoreApplication.translate("MainWindow", u"From this pc...", None))
        self.actionJk_I_ran_out_of_time.setText(QCoreApplication.translate("MainWindow", u"I ran out of time :(", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"X Rotation Speed", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Y Rotation Speed", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Z Rotation Speed", None))
        self.toggleAnimationPushButton.setText(QCoreApplication.translate("MainWindow", u"Toggle Animation", None))
        self.redSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Red Slider", None))
        self.alphaSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Alpha Slider (disabled)", None))
        self.greenSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Green Slider", None))
        self.blueSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Blue Slider", None))
        self.shapeComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Cube", None))
        self.shapeComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Pyramid", None))
        self.shapeComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Tetrahedron", None))
        self.shapeComboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"Octahedron", None))

        self.shapeComboBoxLabel.setText(QCoreApplication.translate("MainWindow", u"Select Shape", None))
        self.surfaceSlidersLabel.setText(QCoreApplication.translate("MainWindow", u"Surface Sliders", None))
        self.greenEdgeSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Green Slider", None))
        self.blueEdgeSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Blue Slider", None))
        self.redEdgeSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Red Slider", None))
        self.edgeSlidersLabel.setText(QCoreApplication.translate("MainWindow", u"Edge Sliders", None))
        self.alphaEdgeSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Alpha Slider (disabled)", None))
        self.extrasLabel.setText(QCoreApplication.translate("MainWindow", u"Extras (Try me!)", None))
        self.rainbowModeRadioButton.setText(QCoreApplication.translate("MainWindow", u"Rainbow Mode", None))
        self.rainbowModeSpeedSliderLabel.setText(QCoreApplication.translate("MainWindow", u"Rainbow Mode Speed", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"Upload Texture", None))
    # retranslateUi

